sudo: false
language: python
addons:
  apt:
    packages:
      - npm
python:
  - "2.7"
  - "3.3"
install:
  - pwd
  - npm install jsdoc
  - pip install tox-travis
script:
  - PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH tox
